# Generated by Django 5.0.1 on 2024-01-18 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("bio", models.TextField()),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("profile_image", models.TextField()),
                ("num_content", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("carousel", "Carousel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.TextField()),
                ("description", models.TextField()),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_content",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
