# Generated by Django 5.0.1 on 2024-01-18 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_content_url_alter_user_is_private_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="InstagramUser",
        ),
    ]
