# Generated by Django 5.0.1 on 2024-01-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_user_instagramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="carousel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="display_url",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")], max_length=10
            ),
        ),
    ]
