# Generated by Django 5.0.1 on 2024-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_content_carousel_content_display_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="categories",
            field=models.TextField(default=[""]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instagramuser",
            name="categories",
            field=models.TextField(default=[""]),
            preserve_default=False,
        ),
    ]
