# Generated by Django 5.0.1 on 2024-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_content_categories_instagramuser_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagramuser",
            name="profile_image",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
